name: Deploy Hugo via rsync

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - uses: actions/checkout@master

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding known_hosts
        run: ssh-keyscan -H victorbilgin.com >> ~/.ssh/known_hosts

      # Set up Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      # Build the site
      - name: Build site
        run: hugo --minify
        
      # Deploy via rsync
      - name: Deploy via rsync
        run: rsync -avz --delete ./public/ ${{ secrets.REMOTE_USER }}@victorbilgin.com:${{ secrets.REMOTE_DIR }}
